In [1]:
import os
import csv
import datetime as dt
import pandas as pd

# index를 날짜로 하는 데이터프레임을 price, adj_price, divend에 대해 반환
def extract_stock_data(file_path, ticker):
    extract_datas = []

    with open(os.path.join(file_path, ticker + '.csv'), newline='') as csvfile:
        reader = csv.reader(csvfile)

        for row in reader:
            extract_datas.append(row)
        
    price_dates = list(map(dt.date.fromisoformat, extract_datas[0]))
    price_history = list(map(float, extract_datas[1]))
    adj_price_dates = list(map(dt.date.fromisoformat, extract_datas[2]))
    adj_price_history = list(map(float, extract_datas[3]))
    divend_dates = list(map(dt.date.fromisoformat, extract_datas[4]))
    divend_history = list(map(float, extract_datas[5]))

    price_df = pd.DataFrame({'date': price_dates, 'price': price_history})
    adj_price_df = pd.DataFrame({'date': adj_price_dates, 'adj_price': adj_price_history})
    divend_df = pd.DataFrame({'date': divend_dates, 'divend': divend_history})

    price_df.set_index('date', inplace=True)
    adj_price_df.set_index('date', inplace=True)
    divend_df.set_index('date', inplace=True)

    return (price_df, adj_price_df, divend_df)

def make_stock_data(file_path, tickers):
    stock_data = []

    for ticker in tickers:
        price_df, adj_price_df, divend_df = extract_stock_data(file_path, ticker)
        stock_df = pd.concat([price_df, adj_price_df, divend_df], axis=1, sort=True)
        stock_df.columns = pd.MultiIndex.from_product([[ticker], stock_df.columns])
        stock_data.append(stock_df)

    stock_data = pd.concat(stock_data, axis=1, sort=True)

    return stock_data

In [2]:
from portfolio import Portfolio

# stock 불러와서 데이터프레임화 하기
file_path = './etf'
tickers = ['QQQ', 'DGRW', 'SCHD', 'SPY', 'SCHG', 'SPYG']
stock_data = make_stock_data(file_path, tickers)
pd.options.display.float_format = '{:.2f}'.format

# test_stock = Portfolio(make_stock_data(file_path, ['QQQ', 'SCHG']), 10000)
test_stock = Portfolio(stock_data, 10000)
portfolio = Portfolio(stock_data, 10000, {"QQQ":56, "SCHD":24, "DGRW":20})

In [3]:
def calc_target_ratio(base_ratio:tuple, etc_ratio:tuple) -> tuple:
    base_sum = sum(base_ratio)
    qqq = base_ratio[0] / base_sum * 100
    etc_sum = sum(etc_ratio)
    etc1 = (etc_ratio[0] / etc_sum) * (base_ratio[1] / base_sum) * 100
    etc2 = (etc_ratio[1] / etc_sum) * (base_ratio[1] / base_sum) * 100

    return (round(qqq, 1), round(etc1, 1), round(etc2, 1))

In [4]:
p = Portfolio(stock_data, 10000, {'QQQ':50, 'SCHD':30, 'DGRW':20})
h, s = p.backtest(duration=5, rebalancing_cycle=5, cash_flow=100, cash_flow_growth=10)

In [8]:
h.to_csv('./abc.csv')

In [ ]:
from joblib import Parallel, delayed
from portfolio_test import portfolio_backtest_by_duration
from portfolio_test import make_benchmark_data

stats = pd.DataFrame(columns=['cagr', 'stdev', 'mdd', 'beta', 'alpha'])
example = Portfolio(stock_data, 10000, {'QQQ':50, 'SCHD':30, 'DGRW':20 })
benchmark = Portfolio(stock_data, 10000, {'QQQ':100})
duration = 5
cash_flow = 700

benchmark_data = make_benchmark_data(benchmark, example.start_date, duration, cash_flow)

param_list = []
for qqq_weight in range(0, 100, 5):
    for schd_weight in range(0, 10):
        ratio_qqq_etc = (qqq_weight, 100 - qqq_weight)
        ratio_schd_dgrw = (schd_weight, 10 - schd_weight)
        ratio_qqq_schd_dgrw = calc_target_ratio(ratio_qqq_etc, ratio_schd_dgrw)
        
        target_ratio = {
            'QQQ': ratio_qqq_schd_dgrw[0],
            'SCHD': ratio_qqq_schd_dgrw[1],
            'DGRW': ratio_qqq_schd_dgrw[2]
        }
        print(target_ratio)
        p = Portfolio(stock_data, 10000, target_ratio)
        param_list.append((p, benchmark_data, None, duration, cash_flow))
        break
    break

results = []
for params in param_list:
    results.append(portfolio_backtest_by_duration(*params))
# with Parallel(n_jobs=-1) as parallel:
#         results = parallel(delayed(portfolio_backtest_by_duration)(*params) for params in param_list)
        
for stat in results:
    stats = pd.concat([stats, stat])

stats

{'QQQ': 0.0, 'SCHD': 0.0, 'DGRW': 100.0}
date
2013-05-22       10000
2013-05-23     9976.91
2013-05-24     9971.48
2013-05-28    10036.67
2013-05-29     9989.13
                ...
2018-05-16   316823.84
2018-05-17   316417.25
2018-05-18   314818.52
2018-05-21   316545.88
2018-05-22   316141.60
Name: (total, value), Length: 1260, dtype: object
               total    cash           QQQ                      SCHD         \
               value   value weight  price number value weight price number
date
2013-05-22     10000       0      0  73.62   0.00  0.00   0.00 11.28   0.00
2013-05-23   9967.87    0.00   0.00  73.45   0.00  0.00   0.00 11.25   0.00
2013-05-24   9967.87    0.00   0.00  73.41   0.00  0.00   0.00 11.27   0.00
2013-05-28  10052.21    0.00   0.00  73.89   0.00  0.00   0.00 11.34   0.00
2013-05-29   9975.90    0.00   0.00  73.54   0.00  0.00   0.00 11.20   0.00
...              ...     ...    ...    ...    ...   ...    ...   ...    ...
2018-05-16 270695.85 7218.77   2.67 168.98   0.00  0.00   0.00 16.48   0.00
2018-05-17 271739.84 7218.77   2.66 168.33   0.00  0.00   0.00 16.51   0.00
2018-05-18 271419.67 7218.77   2.66 167.46   0.00  0.00   0.00 16.46   0.00
2018-05-21 273724.87 7218.77   2.64 168.40   0.00  0.00   0.00 16.62   0.00
2018-05-22 272444.20 7474.90   2.74 168.18   0.00  0.00   0.00 16.53   0.00

                         DGRW
           value weight price  number     value weight
date
2013-05-22  0.00   0.00 24.90  401.61  10000.00 100.00
2013-05-23  0.00   0.00 24.82  401.61   9967.87 100.00
2013-05-24  0.00   0.00 24.82  401.61   9967.87 100.00
2013-05-28  0.00   0.00 25.03  401.61  10052.21 100.00
2013-05-29  0.00   0.00 24.84  401.61   9975.90 100.00
...          ...    ...   ...     ...       ...    ...
2018-05-16  0.00   0.00 41.27 6403.32 264264.94  97.62
2018-05-17  0.00   0.00 41.31 6403.32 264521.07  97.34
2018-05-18  0.00   0.00 41.26 6403.32 264200.90  97.34
2018-05-21  0.00   0.00 41.62 6403.32 266506.10  97.36
2018-05-22  0.00   0.00 41.38 6403.32 264969.30  97.26

[1260 rows x 15 columns]
date
2014-05-22       10000
2014-05-23    10072.85
2014-05-27    10198.36
2014-05-28    10166.98
2014-05-29    10231.98
                ...
2019-05-17   292852.31
2019-05-20   288851.14
2019-05-21   291764.85
2019-05-22   290509.48
2019-05-23   286216.40
Name: (total, value), Length: 1260, dtype: object
               total    cash           QQQ                      SCHD         \
               value   value weight  price number value weight price number
date
2014-05-22     10000       0      0  89.23   0.00  0.00   0.00 12.51   0.00
2014-05-23  10023.29   12.70   0.13  89.88   0.00  0.00   0.00 12.54   0.00
2014-05-27  10069.16   12.70   0.13  91.00   0.00  0.00   0.00 12.57   0.00
2014-05-28  10058.57   12.70   0.13  90.72   0.00  0.00   0.00 12.57   0.00
2014-05-29  10125.62   12.70   0.13  91.30   0.00  0.00   0.00 12.62   0.00
...              ...     ...    ...    ...    ...   ...    ...   ...    ...
2019-05-17 256840.96 2363.57   0.92 183.04   0.00  0.00   0.00 17.35   0.00
2019-05-20 256198.76 2363.57   0.92 179.95   0.00  0.00   0.00 17.25   0.00
2019-05-21 258284.26 2363.57   0.92 181.83   0.00  0.00   0.00 17.38   0.00
2019-05-22 257390.48 2363.57   0.92 181.02   0.00  0.00   0.00 17.31   0.00
2019-05-23 254232.43 2363.57   0.93 178.25   0.00  0.00   0.00 17.14   0.00

                         DGRW
           value weight price  number     value weight
date
2014-05-22  0.00   0.00 28.34  352.86  10000.00 100.00
2014-05-23  0.00   0.00 28.37  352.86  10010.59  99.87
2014-05-27  0.00   0.00 28.50  352.86  10056.46  99.87
2014-05-28  0.00   0.00 28.47  352.86  10045.87  99.87
2014-05-29  0.00   0.00 28.66  352.86  10112.91  99.87
...          ...    ...   ...     ...       ...    ...
2019-05-17  0.00   0.00 42.84 5958.57 255265.25  99.39
2019-05-20  0.00   0.00 42.60 5958.57 253835.19  99.08
2019-05-21  0.00   0.00 42.95 5958.57 255920.69  99.08
2019-05-22  0.00   0.00 42.80 5958.57 255026.91  99.08
2019-05-23  0.00   0.00 42.27 5958.57 251868.86  99.07

[1260 rows x 15 columns]
date
2015-05-22       10000
2015-05-26     9885.04
2015-05-27    10044.36
2015-05-28    10021.73
2015-05-29     9961.98
                ...
2020-05-18   315233.57
2020-05-19   315262.20
2020-05-20   321296.07
2020-05-21   317939.48
2020-05-22   318991.74
Name: (total, value), Length: 1260, dtype: object
               total    cash           QQQ                      SCHD         \
               value   value weight  price number value weight price number
date
2015-05-22     10000       0      0 110.47   0.00  0.00   0.00 13.40   0.00
2015-05-26   9890.80    0.00   0.00 109.20   0.00  0.00   0.00 13.28   0.00
2015-05-27   9984.40    0.00   0.00 110.96   0.00  0.00   0.00 13.37   0.00
2015-05-28   9968.80    0.00   0.00 110.71   0.00  0.00   0.00 13.36   0.00
2015-05-29   9906.40    0.00   0.00 110.05   0.00  0.00   0.00 13.30   0.00
...              ...     ...    ...    ...    ...   ...    ...   ...    ...
2020-05-18 242924.97 3151.42   1.30 227.43   0.00  0.00   0.00 17.10   0.00
2020-05-19 240563.54 3151.42   1.31 226.86   0.00  0.00   0.00 16.82   0.00
2020-05-20 243602.33 3151.42   1.29 231.39   0.00  0.00   0.00 17.03   0.00
2020-05-21 241613.31 3151.42   1.30 228.87   0.00  0.00   0.00 16.88   0.00
2020-05-22 241944.81 3151.42   1.30 229.66   0.00  0.00   0.00 16.90   0.00

                         DGRW
           value weight price  number     value weight
date
2015-05-22  0.00   0.00 32.05  312.01  10000.00 100.00
2015-05-26  0.00   0.00 31.70  312.01   9890.80 100.00
2015-05-27  0.00   0.00 32.00  312.01   9984.40 100.00
2015-05-28  0.00   0.00 31.95  312.01   9968.80 100.00
2015-05-29  0.00   0.00 31.75  312.01   9906.40 100.00
...          ...    ...   ...     ...       ...    ...
2020-05-18  0.00   0.00 43.54 5525.07 240561.41  99.03
2020-05-19  0.00   0.00 42.97 5525.07 237412.12  98.69
2020-05-20  0.00   0.00 43.52 5525.07 240450.91  98.71
2020-05-21  0.00   0.00 43.16 5525.07 238461.88  98.70
2020-05-22  0.00   0.00 43.22 5525.07 238793.39  98.70

[1260 rows x 15 columns]
date
2016-05-23       10000
2016-05-24    10200.32
2016-05-25    10273.68
2016-05-26    10303.77
2016-05-27    10357.38
                ...
2021-05-18   374423.90
2021-05-19   375635.37
2021-05-20   382779.53
2021-05-21   380695.81
2021-05-24   386992.75
Name: (total, value), Length: 1260, dtype: object
               total    cash           QQQ                      SCHD         \
               value   value weight  price number value weight price number
date
2016-05-23     10000       0      0 106.33   0.00  0.00   0.00 13.26   0.00
2016-05-24  10143.74    0.00   0.00 108.46   0.00  0.00   0.00 13.42   0.00
2016-05-25  10218.88    0.00   0.00 109.24   0.00  0.00   0.00 13.50   0.00
2016-05-26  10212.35    0.00   0.00 109.56   0.00  0.00   0.00 13.52   0.00
2016-05-27  10254.82    0.00   0.00 110.13   0.00  0.00   0.00 13.55   0.00
...              ...     ...    ...    ...    ...   ...    ...   ...    ...
2021-05-18 296910.10 8146.74   2.74 322.22   0.00  0.00   0.00 25.52   0.00
2021-05-19 296715.60 8146.74   2.75 322.59   0.00  0.00   0.00 25.42   0.00
2021-05-20 299171.50 8146.74   2.72 328.83   0.00  0.00   0.00 25.57   0.00
2021-05-21 299417.09 8146.74   2.72 327.01   0.00  0.00   0.00 25.60   0.00
2021-05-24 301136.23 8441.45   2.80 332.51   0.00  0.00   0.00 25.68   0.00

                         DGRW
           value weight price  number     value weight
date
2016-05-23  0.00   0.00 30.61  326.69  10000.00 100.00
2016-05-24  0.00   0.00 31.05  326.69  10143.74 100.00
2016-05-25  0.00   0.00 31.28  326.69  10218.88 100.00
2016-05-26  0.00   0.00 31.26  326.69  10212.35 100.00
2016-05-27  0.00   0.00 31.39  326.69  10254.82 100.00
...          ...    ...   ...     ...       ...    ...
2021-05-18  0.00   0.00 58.95 4911.81 289551.21  97.52
2021-05-19  0.00   0.00 58.75 4911.81 288568.85  97.25
2021-05-20  0.00   0.00 59.25 4911.81 291024.76  97.28
2021-05-21  0.00   0.00 59.30 4911.81 291270.35  97.28
2021-05-24  0.00   0.00 59.59 4911.81 292694.77  97.20

[1260 rows x 15 columns]
date
2017-05-22       10000
2017-05-23    10010.07
2017-05-24    10056.12
2017-05-25    10141.73
2017-05-26    10159.71
                ...
2022-05-16   283942.98
2022-05-17   291850.52
2022-05-18   278007.21
2022-05-19   276570.38
2022-05-20   275741.44
Name: (total, value), Length: 1260, dtype: object
               total    cash           QQQ                      SCHD         \
               value   value weight  price number value weight price number
date
2017-05-22     10000       0      0 139.00   0.00  0.00   0.00 14.96   0.00
2017-05-23  10002.77    0.00   0.00 139.14   0.00  0.00   0.00 14.95   0.00
2017-05-24  10022.19    0.00   0.00 139.78   0.00  0.00   0.00 14.98   0.00
2017-05-25  10102.61    0.00   0.00 140.97   0.00  0.00   0.00 15.08   0.00
2017-05-26  10105.38    0.00   0.00 141.22   0.00  0.00   0.00 15.08   0.00
...              ...     ...    ...    ...    ...   ...    ...   ...    ...
2022-05-16 269022.50 6715.90   2.50 298.44   0.00  0.00   0.00 25.52   0.00
2022-05-17 273636.56 6715.90   2.45 306.17   0.00  0.00   0.00 25.98   0.00
2022-05-18 263636.27 6715.90   2.55 291.14   0.00  0.00   0.00 25.17   0.00
2022-05-19 259766.60 6715.90   2.59 289.58   0.00  0.00   0.00 24.80   0.00
2022-05-20 260766.62 6715.90   2.58 288.68   0.00  0.00   0.00 24.91   0.00

                         DGRW
           value weight price  number     value weight
date
2017-05-22  0.00   0.00 36.06  277.32  10000.00 100.00
2017-05-23  0.00   0.00 36.07  277.32  10002.77 100.00
2017-05-24  0.00   0.00 36.14  277.32  10022.19 100.00
2017-05-25  0.00   0.00 36.43  277.32  10102.61 100.00
2017-05-26  0.00   0.00 36.44  277.32  10105.38 100.00
...          ...    ...   ...     ...       ...    ...
2022-05-16  0.00   0.00 60.51 4347.95 263094.46  97.80
2022-05-17  0.00   0.00 61.39 4347.95 266920.65  97.55
2022-05-18  0.00   0.00 59.09 4347.95 256920.37  97.45
2022-05-19  0.00   0.00 58.20 4347.95 253050.69  97.41
2022-05-20  0.00   0.00 58.43 4347.95 254050.72  97.42

[1260 rows x 15 columns]
date
2018-05-21       10000
2018-05-22     9986.94
2018-05-23    10071.26
2018-05-24    10068.29
2018-05-25    10078.38
                ...
2023-05-16   265830.34
2023-05-17   269678.86
2023-05-18   274432.15
2023-05-19   273844.75
2023-05-22   274718.12
Name: (total, value), Length: 1260, dtype: object
               total    cash           QQQ                      SCHD         \
               value   value weight  price number value weight price number
date
2018-05-21     10000       0      0 168.40   0.00  0.00   0.00 16.62   0.00
2018-05-22   9951.95    9.61   0.10 168.18   0.00  0.00   0.00 16.53   0.00
2018-05-23  10002.40    9.61   0.10 169.60   0.00  0.00   0.00 16.57   0.00
2018-05-24   9971.17    9.61   0.10 169.55   0.00  0.00   0.00 16.55   0.00
2018-05-25   9959.15    9.61   0.10 169.72   0.00  0.00   0.00 16.53   0.00
...              ...     ...    ...    ...    ...   ...    ...   ...    ...
2023-05-16 256106.36 3151.42   1.23 327.16   0.00  0.00   0.00 23.06   0.00
2023-05-17 259663.80 3151.42   1.21 331.12   0.00  0.00   0.00 23.39   0.00
2023-05-18 261374.43 3151.42   1.21 337.27   0.00  0.00   0.00 23.51   0.00
2023-05-19 260885.68 3151.42   1.21 336.51   0.00  0.00   0.00 23.53   0.00
2023-05-22 259908.18 3151.42   1.21 337.64   0.00  0.00   0.00 23.53   0.00

                         DGRW
           value weight price  number     value weight
date
2018-05-21  0.00   0.00 41.62  240.27  10000.00 100.00
2018-05-22  0.00   0.00 41.38  240.27   9942.34  99.90
2018-05-23  0.00   0.00 41.59  240.27   9992.79  99.90
2018-05-24  0.00   0.00 41.46  240.27   9961.56  99.90
2018-05-25  0.00   0.00 41.41  240.27   9949.54  99.90
...          ...    ...   ...     ...       ...    ...
2023-05-16  0.00   0.00 62.30 4072.92 253742.79  99.08
2023-05-17  0.00   0.00 62.98 4072.92 256512.38  98.79
2023-05-18  0.00   0.00 63.40 4072.92 258223.00  98.79
2023-05-19  0.00   0.00 63.28 4072.92 257734.25  98.79
2023-05-22  0.00   0.00 63.04 4072.92 256756.75  98.79

[1260 rows x 15 columns]
date
2019-05-21       10000
2019-05-22     9955.45
2019-05-23     9803.11
2019-05-24     9798.16
2019-05-28     9761.32
                ...
2024-05-15   315468.26
2024-05-16   315638.48
2024-05-17   315490.78
2024-05-20   317605.53
2024-05-21   318203.03
Name: (total, value), Length: 1260, dtype: object
               total     cash           QQQ                      SCHD         \
               value    value weight  price number value weight price number
date
2019-05-21     10000        0      0 181.83   0.00  0.00   0.00 17.38   0.00
2019-05-22   9965.08     0.00   0.00 181.02   0.00  0.00   0.00 17.31   0.00
2019-05-23   9841.68     0.00   0.00 178.25   0.00  0.00   0.00 17.14   0.00
2019-05-24   9855.65     0.00   0.00 178.16   0.00  0.00   0.00 17.13   0.00
2019-05-28   9735.74    29.10   0.30 177.49   0.00  0.00   0.00 16.87   0.00
...              ...      ...    ...    ...    ...   ...    ...   ...    ...
2024-05-15 282839.69 11359.73   4.02 452.90   0.00  0.00   0.00 26.72   0.00
2024-05-16 283130.83 11359.73   4.01 451.98   0.00  0.00   0.00 26.67   0.00
2024-05-17 283308.23 11359.73   4.01 451.76   0.00  0.00   0.00 26.69   0.00
2024-05-20 283166.31 11359.73   4.01 454.91   0.00  0.00   0.00 26.56   0.00
2024-05-21 283450.15 11359.73   4.01 455.80   0.00  0.00   0.00 26.49   0.00

                         DGRW
           value weight price  number     value weight
date
2019-05-21  0.00   0.00 42.95  232.83  10000.00 100.00
2019-05-22  0.00   0.00 42.80  232.83   9965.08 100.00
2019-05-23  0.00   0.00 42.27  232.83   9841.68 100.00
2019-05-24  0.00   0.00 42.33  232.83   9855.65 100.00
2019-05-28  0.00   0.00 41.69  232.83   9706.64  99.70
...          ...    ...   ...     ...       ...    ...
2024-05-15  0.00   0.00 76.74 3547.93 272267.82  96.26
2024-05-16  0.00   0.00 76.60 3547.93 271771.11  95.99
2024-05-17  0.00   0.00 76.65 3547.93 271948.50  95.99
2024-05-20  0.00   0.00 76.61 3547.93 271806.59  95.99
2024-05-21  0.00   0.00 76.69 3547.93 272090.42  95.99

[1260 rows x 15 columns]
date
2020-05-20       10000
2020-05-21     9891.09
2020-05-22     9925.23
2020-05-26     9898.44
2020-05-27     9952.46
                ...
2025-05-19   296701.86
2025-05-20   296538.79
2025-05-21   292587.57
2025-05-22   293112.21
2025-05-23   290510.86
Name: (total, value), Length: 1260, dtype: object
               total    cash           QQQ                      SCHD         \
               value   value weight  price number value weight price number
date
2020-05-20     10000       0      0 231.39   0.00  0.00   0.00 17.03   0.00
2020-05-21   9917.28    0.00   0.00 228.87   0.00  0.00   0.00 16.88   0.00
2020-05-22   9931.07    0.00   0.00 229.66   0.00  0.00   0.00 16.90   0.00
2020-05-26  10062.04   16.08   0.16 229.04   0.00  0.00   0.00 17.20   0.00
2020-05-27  10236.67   16.08   0.16 230.29   0.00  0.00   0.00 17.58   0.00
...              ...     ...    ...    ...    ...   ...    ...   ...    ...
2025-05-19 269672.97 5806.36   2.15 522.01   0.00  0.00   0.00 26.58   0.00
2025-05-20 269619.11 5806.36   2.15 520.27   0.00  0.00   0.00 26.48   0.00
2025-05-21 265410.54 5806.36   2.19 513.04   0.00  0.00   0.00 26.01   0.00
2025-05-22 265054.43 5806.36   2.19 514.00   0.00  0.00   0.00 25.96   0.00
2025-05-23 263791.86 5806.36   2.20 509.24   0.00  0.00   0.00 25.89   0.00

                         DGRW
           value weight price  number     value weight
date
2020-05-20  0.00   0.00 43.52  229.78  10000.00 100.00
2020-05-21  0.00   0.00 43.16  229.78   9917.28 100.00
2020-05-22  0.00   0.00 43.22  229.78   9931.07 100.00
2020-05-26  0.00   0.00 43.72  229.78  10045.96  99.84
2020-05-27  0.00   0.00 44.48  229.78  10220.59  99.84
...          ...    ...   ...     ...       ...    ...
2025-05-19  0.00   0.00 81.75 3237.36 264654.47  98.14
2025-05-20  0.00   0.00 81.49 3237.36 263812.76  97.85
2025-05-21  0.00   0.00 80.19 3237.36 259604.18  97.81
2025-05-22  0.00   0.00 80.08 3237.36 259248.07  97.81
2025-05-23  0.00   0.00 79.69 3237.36 257985.50  97.80

[1260 rows x 15 columns]
date
2021-05-20       10000
2021-05-21     9944.65
2021-05-24    10111.91
2021-05-25    10125.90
2021-05-26    10161.18
                ...
2026-05-18   346965.53
2026-05-19   344933.71
2026-05-20   350361.26
2026-05-21   351784.35
2026-05-22   353199.62
Name: (total, value), Length: 1258, dtype: object
               total     cash           QQQ                      SCHD         \
               value    value weight  price number value weight price number
date
2021-05-20     10000        0      0 328.83   0.00  0.00   0.00 25.57   0.00
2021-05-21  10008.44     0.00   0.00 327.01   0.00  0.00   0.00 25.60   0.00
2021-05-24  10067.51    10.13   0.10 332.51   0.00  0.00   0.00 25.68   0.00
2021-05-25  10025.32    10.13   0.10 332.97   0.00  0.00   0.00 25.50   0.00
2021-05-26  10020.25    10.13   0.10 334.13   0.00  0.00   0.00 25.50   0.00
...              ...      ...    ...    ...    ...   ...    ...   ...    ...
2026-05-18 276806.56 12645.42   4.57 705.88   0.00  0.00   0.00 32.04   0.00
2026-05-19 275482.44 12645.42   4.59 701.53   0.00  0.00   0.00 32.10   0.00
2026-05-20 277082.42 13433.27   4.85 713.15   0.00  0.00   0.00 32.12   0.00
2026-05-21 278146.13 13433.27   4.83 714.51   0.00  0.00   0.00 32.25   0.00
2026-05-22 279166.80 13433.27   4.81 717.54   0.00  0.00   0.00 32.83   0.00

                         DGRW
           value weight price  number     value weight
date
2021-05-20  0.00   0.00 59.25  168.78  10000.00 100.00
2021-05-21  0.00   0.00 59.30  168.78  10008.44 100.00
2021-05-24  0.00   0.00 59.59  168.78  10057.38  99.90
2021-05-25  0.00   0.00 59.34  168.78  10015.19  99.90
2021-05-26  0.00   0.00 59.31  168.78  10010.13  99.90
...          ...    ...   ...     ...       ...    ...
2026-05-18  0.00   0.00 95.76 2758.58 264161.14  95.43
2026-05-19  0.00   0.00 95.28 2758.58 262837.03  95.41
2026-05-20  0.00   0.00 95.86 2758.58 264437.00  95.44
2026-05-21  0.00   0.00 95.96 2758.58 264712.86  95.17
2026-05-22  0.00   0.00 96.33 2758.58 265733.53  95.19

[1258 rows x 15 columns]

   cagr stdev   mdd beta alpha            ratio
0 93.67 16.00 10.00 0.81  9.52  00.0:00.0:100.0
1 91.01 16.39 14.36 0.78 11.93  00.0:00.0:100.0
2 89.12 21.02 29.93 0.83  5.98  00.0:00.0:100.0
3 97.58 20.67 30.08 0.78 10.78  00.0:00.0:100.0
4 91.98 20.94 29.13 0.72 16.58  00.0:00.0:100.0
5 91.85 22.29 27.71 0.71 17.43  00.0:00.0:100.0
6 95.21 21.14 23.91 0.70 17.93  00.0:00.0:100.0
7 92.42 17.91 12.84 0.61 23.54  00.0:00.0:100.0
8 94.82 17.67 12.97 0.64 20.44  00.0:00.0:100.0

In [35]:
stats.to_csv('./stats_qqq_schd_dgrw.csv')

In [61]:
stats = pd.read_csv('./stats_qqq_schd_dgrw.csv', index_col=0)
stats

In [96]:
weight_map = {0: 1.0, 1: 1.0, 2: 1.0, 3: 1.0, 4: 1.0,
              5: 1.1, 6: 1.1,
              7: 1.2, 8: 1.2}

stats['weight'] = stats.index.map(lambda x: weight_map[x % 9])
stats

def weighted_alpha_mean(group):
    d = group['alpha']
    w = group['weight']
    return (d * w).sum() / w.sum()

weighted_alpha_stat = stats.groupby('ratio').apply(weighted_alpha_mean)
weighted_alpha_stat = weighted_alpha_stat.sort_values(ascending=False)
mdd_stat = stats.groupby('ratio')['mdd'].quantile(0.25)

pd.set_option('display.max_rows', None)
mdd_stat

ratio
0.0:0.0:100.0    16.93
0.0:10.0:90.0    16.94
0.0:20.0:80.0    16.94
0.0:30.0:70.0    16.97
0.0:40.0:60.0    16.95
0.0:50.0:50.0    16.68
0.0:60.0:40.0    16.66
0.0:70.0:30.0    16.63
0.0:80.0:20.0    16.50
0.0:90.0:10.0    16.38
05.0:0.0:95.0    17.77
05.0:19.0:76.0   17.79
05.0:28.5:66.5   17.80
05.0:38.0:57.0   17.75
05.0:47.5:47.5   17.78
05.0:57.0:38.0   17.50
05.0:66.5:28.5   17.24
05.0:76.0:19.0   17.19
05.0:85.5:9.5    17.11
05.0:9.5:85.5    17.77
10.0:0.0:90.0    18.29
10.0:18.0:72.0   18.59
10.0:27.0:63.0   18.55
10.0:36.0:54.0   18.37
10.0:45.0:45.0   18.31
10.0:54.0:36.0   18.12
10.0:63.0:27.0   18.01
10.0:72.0:18.0   17.90
10.0:81.0:9.0    17.93
10.0:9.0:81.0    18.23
15.0:0.0:85.0    19.22
15.0:17.0:68.0   19.41
15.0:25.5:59.5   19.29
15.0:34.0:51.0   19.21
15.0:42.5:42.5   19.06
15.0:51.0:34.0   18.93
15.0:59.5:25.5   18.81
15.0:68.0:17.0   19.43
15.0:76.5:8.5    18.82
15.0:8.5:76.5    19.41
20.0:0.0:80.0    20.21
20.0:16.0:64.0   20.20
20.0:24.0:56.0   20.12
20.0:32.0:48.0   19.97
20.0:40.0:40.0   19.84
20.0:48.0:32.0   19.77
20.0:56.0:24.0   19.91
20.0:64.0:16.0   19.92
20.0:72.0:8.0    19.86
20.0:8.0:72.0    20.14
25.0:0.0:75.0    21.16
25.0:15.0:60.0   20.92
25.0:22.5:52.5   20.95
25.0:30.0:45.0   20.78
25.0:37.5:37.5   20.66
25.0:45.0:30.0   20.70
25.0:52.5:22.5   20.49
25.0:60.0:15.0   20.44
25.0:67.5:7.5    20.39
25.0:7.5:67.5    21.01
30.0:0.0:70.0    22.01
30.0:14.0:56.0   21.91
30.0:21.0:49.0   21.65
30.0:28.0:42.0   21.52
30.0:35.0:35.0   21.56
30.0:42.0:28.0   21.59
30.0:49.0:21.0   21.40
30.0:56.0:14.0   21.45
30.0:63.0:7.0    21.41
30.0:7.0:63.0    21.97
35.0:0.0:65.0    22.92
35.0:13.0:52.0   22.69
35.0:19.5:45.5   22.63
35.0:26.0:39.0   22.55
35.0:32.5:32.5   22.30
35.0:39.0:26.0   22.42
35.0:45.5:19.5   22.34
35.0:52.0:13.0   22.33
35.0:58.5:6.5    22.28
35.0:6.5:58.5    22.77
40.0:0.0:60.0    23.66
40.0:12.0:48.0   23.70
40.0:18.0:42.0   23.45
40.0:24.0:36.0   23.36
40.0:30.0:30.0   23.30
40.0:36.0:24.0   23.23
40.0:42.0:18.0   23.12
40.0:48.0:12.0   22.78
40.0:54.0:6.0    22.69
40.0:6.0:54.0    23.60
45.0:0.0:55.0    24.56
45.0:11.0:44.0   24.33
45.0:16.5:38.5   24.37
45.0:22.0:33.0   24.24
45.0:27.5:27.5   24.13
45.0:33.0:22.0   24.07
45.0:38.5:16.5   24.01
45.0:44.0:11.0   23.92
45.0:49.5:5.5    23.97
45.0:5.5:49.5    24.36
50.0:0.0:50.0    25.32
50.0:10.0:40.0   25.19
50.0:15.0:35.0   25.11
50.0:20.0:30.0   25.13
50.0:25.0:25.0   25.03
50.0:30.0:20.0   25.06
50.0:35.0:15.0   24.79
50.0:40.0:10.0   25.00
50.0:45.0:5.0    24.87
50.0:5.0:45.0    25.26
55.0:0.0:45.0    26.39
55.0:13.5:31.5   26.12
55.0:18.0:27.0   26.10
55.0:22.5:22.5   26.04
55.0:27.0:18.0   25.99
55.0:31.5:13.5   26.00
55.0:36.0:9.0    25.97
55.0:4.5:40.5    26.30
55.0:40.5:4.5    25.66
55.0:9.0:36.0    26.19
60.0:0.0:40.0    27.21
60.0:12.0:28.0   27.37
60.0:16.0:24.0   27.18
60.0:20.0:20.0   27.15
60.0:24.0:16.0   27.01
60.0:28.0:12.0   27.04
60.0:32.0:8.0    26.95
60.0:36.0:4.0    26.93
60.0:4.0:36.0    27.52
60.0:8.0:32.0    27.47
65.0:0.0:35.0    28.47
65.0:10.5:24.5   28.32
65.0:14.0:21.0   28.24
65.0:17.5:17.5   28.13
65.0:21.0:14.0   28.06
65.0:24.5:10.5   28.04
65.0:28.0:7.0    27.94
65.0:3.5:31.5    28.41
65.0:31.5:3.5    27.89
65.0:7.0:28.0    28.42
70.0:0.0:30.0    29.28
70.0:12.0:18.0   29.19
70.0:15.0:15.0   29.23
70.0:18.0:12.0   29.09
70.0:21.0:9.0    28.99
70.0:24.0:6.0    28.92
70.0:27.0:3.0    28.92
70.0:3.0:27.0    29.30
70.0:6.0:24.0    29.23
70.0:9.0:21.0    29.26
75.0:0.0:25.0    29.22
75.0:10.0:15.0   29.28
75.0:12.5:12.5   29.37
75.0:15.0:10.0   29.35
75.0:17.5:7.5    29.46
75.0:2.5:22.5    29.25
75.0:20.0:5.0    29.51
75.0:22.5:2.5    29.56
75.0:5.0:20.0    29.31
75.0:7.5:17.5    29.26
80.0:0.0:20.0    28.82
80.0:10.0:10.0   29.01
80.0:12.0:8.0    29.05
80.0:14.0:6.0    29.09
80.0:16.0:4.0    29.11
80.0:18.0:2.0    29.12
80.0:2.0:18.0    28.85
80.0:4.0:16.0    28.87
80.0:6.0:14.0    28.90
80.0:8.0:12.0    28.97
85.0:0.0:15.0    28.37
85.0:1.5:13.5    28.40
85.0:10.5:4.5    28.60
85.0:12.0:3.0    28.63
85.0:13.5:1.5    28.66
85.0:3.0:12.0    28.48
85.0:4.5:10.5    28.51
85.0:6.0:9.0     28.53
85.0:7.5:7.5     28.55
85.0:9.0:6.0     28.57
90.0:0.0:10.0    28.07
90.0:1.0:9.0     28.09
90.0:2.0:8.0     28.10
90.0:3.0:7.0     28.12
90.0:4.0:6.0     28.14
90.0:5.0:5.0     28.15
90.0:6.0:4.0     28.17
90.0:7.0:3.0     28.18
90.0:8.0:2.0     28.20
90.0:9.0:1.0     28.22
95.0:0.0:5.0     27.97
95.0:0.5:4.5     27.98
95.0:1.0:4.0     27.98
95.0:1.5:3.5     27.99
95.0:2.0:3.0     28.00
95.0:2.5:2.5     28.00
95.0:3.0:2.0     28.01
95.0:3.5:1.5     28.02
95.0:4.0:1.0     28.02
95.0:4.5:0.5     28.03
Name: mdd, dtype: float64

In [101]:
stat_summary = stats.groupby(['ratio']).mean()
stat_summary['alpha'] = weighted_alpha_stat
stat_summary['mdd_median'] = mdd_stat
stat_summary['mdd_diff'] = stat_summary['mdd'] - stat_summary['mdd_median']
stat_summary = stat_summary.sort_values(by='alpha', ascending=False)
stat_summary = stat_summary[stat_summary['alpha'] > 0]
stat_summary.sort_values(by='mdd_diff', ascending=False, inplace=True)
stat_summary[(stat_summary['cagr'] > 14.5)]

                cagr  stdev   mdd  beta  alpha  weight  mdd_median  mdd_diff
ratio
35.0:32.5:32.5 14.52  17.34 25.40  0.75   0.13    1.07       22.30      3.10
35.0:39.0:26.0 14.52  17.32 25.43  0.74   0.19    1.07       22.42      3.01
35.0:19.5:45.5 14.59  17.47 25.53  0.76   0.01    1.07       22.63      2.90
35.0:26.0:39.0 14.57  17.40 25.45  0.75   0.08    1.07       22.55      2.90
40.0:54.0:6.0  14.71  17.52 25.58  0.75   0.26    1.07       22.69      2.89
40.0:48.0:12.0 14.78  17.53 25.56  0.75   0.25    1.07       22.78      2.78
40.0:42.0:18.0 14.82  17.56 25.59  0.76   0.21    1.07       23.12      2.48
40.0:36.0:24.0 14.83  17.58 25.59  0.76   0.16    1.07       23.23      2.36
40.0:30.0:30.0 14.86  17.61 25.60  0.77   0.11    1.07       23.30      2.31
40.0:24.0:36.0 14.91  17.66 25.61  0.77   0.08    1.07       23.36      2.25
40.0:18.0:42.0 14.94  17.73 25.68  0.78   0.03    1.07       23.45      2.23
45.0:44.0:11.0 15.07  17.80 25.79  0.77   0.18    1.07       23.92      1.87
45.0:49.5:5.5  15.07  17.79 25.76  0.77   0.24    1.07       23.97      1.79
45.0:38.5:16.5 15.12  17.84 25.79  0.78   0.15    1.07       24.01      1.79
45.0:33.0:22.0 15.17  17.87 25.77  0.78   0.13    1.07       24.07      1.70
45.0:27.5:27.5 15.20  17.92 25.77  0.79   0.09    1.07       24.13      1.64
45.0:22.0:33.0 15.24  17.98 25.82  0.79   0.05    1.07       24.24      1.58
45.0:16.5:38.5 15.30  18.02 25.83  0.80   0.04    1.07       24.37      1.46
45.0:11.0:44.0 15.35  18.05 25.77  0.80   0.04    1.07       24.33      1.43
45.0:5.5:49.5  15.40  18.11 25.75  0.80   0.03    1.07       24.36      1.39
50.0:35.0:15.0 15.52  18.13 25.90  0.80   0.19    1.07       24.79      1.11
50.0:45.0:5.0  15.41  18.07 25.97  0.79   0.21    1.07       24.87      1.10
50.0:40.0:10.0 15.44  18.09 25.95  0.79   0.18    1.07       25.00      0.95
50.0:25.0:25.0 15.58  18.23 25.97  0.81   0.12    1.07       25.03      0.94
50.0:30.0:20.0 15.51  18.17 25.98  0.80   0.12    1.07       25.06      0.92
50.0:10.0:40.0 15.70  18.40 26.03  0.82   0.04    1.07       25.19      0.84
50.0:15.0:35.0 15.65  18.32 25.95  0.81   0.06    1.07       25.11      0.83
50.0:20.0:30.0 15.62  18.28 25.97  0.81   0.09    1.07       25.13      0.83
55.0:40.5:4.5  15.78  18.40 26.10  0.81   0.19    1.07       25.66      0.44
55.0:22.5:22.5 15.80  18.56 26.28  0.83   0.00    1.07       26.04      0.25
55.0:36.0:9.0  15.82  18.43 26.14  0.82   0.17    1.07       25.97      0.17
55.0:27.0:18.0 15.85  18.50 26.16  0.82   0.10    1.07       25.99      0.17
55.0:31.5:13.5 15.83  18.47 26.16  0.82   0.13    1.07       26.00      0.16
90.0:6.0:4.0   17.93  20.95 28.16  0.96   0.02    1.07       28.17     -0.01
90.0:7.0:3.0   17.93  20.94 28.15  0.95   0.02    1.07       28.18     -0.04
90.0:8.0:2.0   17.93  20.93 28.14  0.95   0.03    1.07       28.20     -0.06
90.0:9.0:1.0   17.93  20.91 28.13  0.95   0.04    1.07       28.22     -0.09
85.0:0.0:15.0  17.81  20.82 27.94  0.95   0.02    1.07       28.37     -0.43
85.0:1.5:13.5  17.82  20.80 27.93  0.95   0.04    1.07       28.40     -0.47
85.0:3.0:12.0  17.82  20.78 27.92  0.95   0.04    1.07       28.48     -0.56
85.0:4.5:10.5  17.81  20.76 27.90  0.95   0.05    1.07       28.51     -0.60
85.0:6.0:9.0   17.81  20.74 27.89  0.94   0.06    1.07       28.53     -0.64
60.0:36.0:4.0  16.10  18.71 26.26  0.83   0.16    1.07       26.93     -0.68
85.0:7.5:7.5   17.80  20.72 27.87  0.94   0.06    1.07       28.55     -0.68
60.0:32.0:8.0  16.15  18.75 26.26  0.84   0.15    1.07       26.95     -0.69
85.0:9.0:6.0   17.81  20.70 27.86  0.94   0.09    1.07       28.57     -0.72
60.0:24.0:16.0 16.20  18.83 26.27  0.84   0.11    1.07       27.01     -0.74
85.0:10.5:4.5  17.81  20.68 27.84  0.94   0.10    1.07       28.60     -0.76
60.0:28.0:12.0 16.16  18.79 26.27  0.84   0.12    1.07       27.04     -0.76
85.0:12.0:3.0  17.83  20.64 27.84  0.94   0.14    1.07       28.63     -0.80
85.0:13.5:1.5  17.83  20.63 27.82  0.94   0.15    1.07       28.66     -0.84
60.0:20.0:20.0 16.23  18.87 26.30  0.85   0.09    1.07       27.15     -0.85
80.0:0.0:20.0  17.59  20.57 27.67  0.94   0.00    1.07       28.82     -1.15
80.0:2.0:18.0  17.59  20.54 27.65  0.93   0.01    1.07       28.85     -1.20
80.0:4.0:16.0  17.56  20.50 27.63  0.93   0.02    1.07       28.87     -1.24
80.0:6.0:14.0  17.57  20.46 27.62  0.93   0.05    1.07       28.90     -1.28
80.0:8.0:12.0  17.57  20.42 27.61  0.93   0.09    1.07       28.97     -1.36
65.0:21.0:14.0 16.48  19.25 26.65  0.87   0.02    1.07       28.06     -1.41
80.0:10.0:10.0 17.56  20.40 27.59  0.93   0.09    1.07       29.01     -1.42
65.0:28.0:7.0  16.48  19.13 26.50  0.86   0.12    1.07       27.94     -1.44
65.0:31.5:3.5  16.47  19.08 26.43  0.86   0.17    1.07       27.89     -1.46
65.0:24.5:10.5 16.50  19.19 26.56  0.86   0.08    1.07       28.04     -1.48
80.0:12.0:8.0  17.53  20.38 27.57  0.93   0.08    1.07       29.05     -1.48
65.0:17.5:17.5 16.53  19.30 26.64  0.87   0.01    1.07       28.13     -1.49
80.0:14.0:6.0  17.51  20.36 27.56  0.93   0.08    1.07       29.09     -1.53
80.0:16.0:4.0  17.50  20.31 27.55  0.92   0.10    1.07       29.11     -1.57
80.0:18.0:2.0  17.44  20.24 27.51  0.92   0.09    1.07       29.12     -1.61
70.0:27.0:3.0  16.79  19.55 26.87  0.88   0.06    1.07       28.92     -2.05
70.0:24.0:6.0  16.79  19.58 26.86  0.88   0.03    1.07       28.92     -2.07
75.0:10.0:15.0 17.20  20.03 27.19  0.91   0.02    1.07       29.28     -2.10
70.0:21.0:9.0  16.79  19.61 26.86  0.89   0.01    1.07       28.99     -2.13
75.0:12.5:12.5 17.18  20.01 27.19  0.91   0.03    1.07       29.37     -2.18
75.0:15.0:10.0 17.17  19.98 27.16  0.91   0.04    1.07       29.35     -2.19
70.0:18.0:12.0 16.82  19.64 26.88  0.89   0.01    1.07       29.09     -2.21
75.0:17.5:7.5  17.16  19.95 27.14  0.90   0.06    1.07       29.46     -2.32
75.0:20.0:5.0  17.12  19.93 27.14  0.90   0.04    1.07       29.51     -2.37
75.0:22.5:2.5  17.09  19.90 27.13  0.90   0.04    1.07       29.56     -2.44

In [41]:
pd.set_option('display.max_rows', None)

stat_summary_sorted = stat_summary.sort_values(by=['alpha'], ascending=False)
stat_summary_sorted = stat_summary_sorted[stat_summary_sorted['alpha'] > 0]
stat_sorted = stats.sort_values(by=['ratio', 'alpha'], ascending=[True, False])

In [ ]:
import seaborn as sns

sns.catplot(data=stats, x='ratio', y='cagr', kind='box')
sns.catplot(data=stats, x='ratio', y='stdev', kind='box')
sns.catplot(data=stats, x='ratio', y='mdd', kind='box')

In [ ]:
sns.relplot(data=test, x='stdev', y='cagr', hue='ratio')

In [ ]:
sns.relplot(data=stats, x='stdev', y='cagr', hue='ratio')